---
name: Validate component

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  validate-esp-idf-lib-component:
    uses: https://github.com/esp-idf-lib/shared-workflows/.github/workflows/validate-component.yml@main
